# Generated by Django 3.0 on 2021-02-27 11:50

import atm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piris', '0006_auto_20210227_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('pin', models.CharField(default=atm.models._createHash, max_length=10, unique=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='piris.CreditAccount')),
            ],
        ),
    ]
