# Generated by Django 3.0 on 2021-02-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('PRC', 'percentages'), ('ACT', 'active_card'), ('DEP', 'deposit')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3),
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=14)),
                ('initial_price', models.CharField(max_length=35)),
                ('current_price', models.CharField(max_length=35)),
                ('final_price', models.CharField(max_length=35)),
                ('income', models.CharField(max_length=35)),
                ('account_type', models.CharField(choices=[('PRC', 'percentages'), ('ACT', 'active_card'), ('DEP', 'deposit')], max_length=35)),
                ('base_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piris.PlanOfBaseAccounts')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_contract', to='piris.BankCreditContract')),
            ],
        ),
    ]
