# Generated by Django 3.0 on 2021-02-23 20:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piris', '0002_auto_20210223_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='payments',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=1), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('DEP', 'deposit'), ('PRC', 'percentages'), ('ACT', 'active_card')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('BYN', 'BYN')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('BYN', 'BYN')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='type',
            field=models.CharField(choices=[('URG', 'Срочный'), ('UD', 'До восстребования')], max_length=35),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='account_type',
            field=models.CharField(choices=[('DEP', 'deposit'), ('PRC', 'percentages'), ('ACT', 'active_card')], max_length=35),
        ),
    ]
