# Generated by Django 3.0 on 2021-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piris', '0003_auto_20210223_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('PRC', 'percentages'), ('ACT', 'active_card'), ('DEP', 'deposit')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='type',
            field=models.CharField(choices=[('ANN', 'annuity'), ('DIF', 'differentiated')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('BYN', 'BYN'), ('USD', 'USD')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='account_type',
            field=models.CharField(choices=[('PRC', 'percentages'), ('ACT', 'active_card'), ('DEP', 'deposit')], max_length=35),
        ),
    ]
