# Generated by Django 3.0 on 2021-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piris', '0004_auto_20210223_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('ACT', 'active_card'), ('DEP', 'deposit'), ('PRC', 'percentages')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='type',
            field=models.CharField(choices=[('DIF', 'differentiated'), ('ANN', 'annuity')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='currency',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('EUR', 'EUR')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='account_type',
            field=models.CharField(choices=[('ACT', 'active_card'), ('DEP', 'deposit'), ('PRC', 'percentages')], max_length=35),
        ),
        migrations.AlterField(
            model_name='planofbaseaccounts',
            name='activity',
            field=models.CharField(choices=[('P', 'passive'), ('A', 'active')], max_length=35),
        ),
    ]
