# Generated by Django 3.0 on 2021-02-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piris', '0005_auto_20210224_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('ACT', 'active_card'), ('PRC', 'percentages'), ('DEP', 'deposit')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('BYN', 'BYN')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankcreditcontract',
            name='type',
            field=models.CharField(choices=[('ANN', 'annuity'), ('DIF', 'differentiated')], max_length=35),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('BYN', 'BYN')], default='BYN', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankpersonalcontract',
            name='type',
            field=models.CharField(choices=[('UD', 'До восстребования'), ('URG', 'Срочный')], max_length=35),
        ),
        migrations.AlterField(
            model_name='creditaccount',
            name='account_type',
            field=models.CharField(choices=[('ACT', 'active_card'), ('PRC', 'percentages'), ('DEP', 'deposit')], max_length=35),
        ),
        migrations.AlterField(
            model_name='planofbaseaccounts',
            name='activity',
            field=models.CharField(choices=[('A', 'active'), ('P', 'passive')], max_length=35),
        ),
    ]
